server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  add_header X-Antrasha-App "work" always;

  location = /site.webmanifest {
    default_type application/manifest+json;
    add_header X-Antrasha-App "work" always;
    add_header Cache-Control "no-cache" always;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
